export const playerNameTestCases: Record<string, boolean> = {
    "€": false,
    "1": false,
    "10 BB": false,
    "12 BB": false,
    "$18,150": false,
    "18 BB": false,
    "19%": false,
    "19 BB": false,
    "<1 BB": false,
    "$20,900": false,
    "$21,825": false,
    "$24,125": false,
    "26%": false,
    "$26,375": false,
    "29%": false,
    "$34,975": false,
    "35%": false,
    "$35,570": false,
    "$35,875": false,
    "38%": false,
    "3COIN": true,
    "4": false,
    "4 HILARY": true,
    "4 WATER Global": false,
    "55%": false,
    "$58,275": false,
    "64%": false,
    "6 FEET UNDER": true,
    "7": false,
    "73075": false,
    "$77,225": false,
    "7 BB": false,
    "8 BB": false,
    "9%": false,
    "9 BB": false,
    a: false,
    AA: true,
    AARON: true,
    AB: true,
    "ACE POKER": true,
    "ACTION DAN": true,
    "ACTION KEN": true,
    ADAM: true,
    ADAM22: true,
    "ADAM OG": true,
    adidas: false,
    AIRIKA: true,
    AJ: true,
    "AK PLUS": true,
    AL: true,
    ALA: true,
    ALAN: true,
    ALEC: true,
    "ALEC TORELLI": true,
    ALEX: true,
    ALEXANDRA: true,
    ALFIE: true,
    ALI: true,
    "ALI G": true,
    "ALL OF IT": true,
    ALOE: true,
    AMANDA: true,
    AMBER: true,
    ANDERS: true,
    ANDREW: true,
    ANDY: true,
    "ANDY O": true,
    ANGELIQUE: true,
    ANTHONY: true,
    ANTONIO: true,
    ANTONIOUS: true,
    ANTWAN: true,
    ANY2TOMMY: true,
    AP: true,
    ARBI: true,
    ARDEN: true,
    ARI: true,
    ARIEL: true,
    ARMAN: true,
    "ARMENIAN MATT": true,
    "ARMENIAN MIKE": true,
    ART: true,
    "ASH KARDASH": true,
    ASHLEY: true,
    "ATC AARON": true,
    "AUSSIE AL": true,
    "AUSSIE MATT": true,
    AUSTIN: true,
    "A.V.": true,
    "    A.V. GOODDAY": true,
    "A.V. SLEEPS": true,
    "a WESLEY": false,
    AYAKA: true,
    BABA: true,
    "BABY GIRL": true,
    "BAD BRAD": true,
    BANK: true,
    BARRY: true,
    "BARRY JR.": true,
    "    BARSTOOL NATE": true,
    BART: true,
    "BEANIE MAN": true,
    BEANZ: true,
    BEAR: true,
    "BEAR JEW": true,
    BEN: true,
    "BENNY BLANCO": true,
    "BIG AL": true,
    "BIG CAT": true,
    "BIG DADDY CHAZ": true,
    "BIG FAT FISH": true,
    "BIG JOHN": true,
    "BIG RICK": true,
    BILL: true,
    BILLY: true,
    BING: true,
    "BING BONG": true,
    "BLANK CHECK BEN": true,
    BOB: true,
    BOBBY: true,
    BOBO: true,
    BOJIDAR: true,
    BONES: true,
    BORIS: true,
    "BOSTON JIMMY": true,
    BOTEZ: true,
    "BOUNTY POOL": false,
    BOXBOX: true,
    BRAD: true,
    BRANDON: true,
    BRANTZEN: true,
    BRAYDEN: true,
    "BRAZIL GOD": true,
    BRETT: true,
    BRETTIE: true,
    BRETTSKI: true,
    BRIAN: true,
    BRICK: true,
    BRITNEY: true,
    "BRONX BOMBER": true,
    "BROWN BALLA": true,
    BRUCE: true,
    BRYAN: true,
    BRYCE: true,
    "BRYCE HALL": true,
    BTRFLY: true,
    "BTS NATE": true,
    BUDDY: true,
    BUTTERFLI: true,
    BUTTONCLICKR: true,
    "BY ALEX": true,
    C: false,
    C2B: true,
    CAITLIN: true,
    CALVIN: true,
    CANDIE: true,
    CARLY: true,
    CASEY: true,
    CASINO: true,
    "CASINO KING": true,
    CASPER: true,
    CHAD: true,
    CHAMATH: true,
    CHANDLER: true,
    CHARLES: true,
    CHARLIE: true,
    CHEN: true,
    CHERISH: true,
    CHIN: true,
    CHIRP: true,
    CHRIS: true,
    "CHRIS H": true,
    "CHRIS RUSSIAN": true,
    CHRISTIAN: true,
    CLAYTON: true,
    "COACH BEN": true,
    CODY: true,
    "COINFLEX MAN": true,
    COLE: true,
    COLIN: true,
    COLLEEN: true,
    CONNOR: true,
    "COOKIE MONSTER": true,
    "COWBOY JOHN": true,
    CRAIG: true,
    "CRAZY DREW": true,
    "CRAZY JIM": true,
    "C RONNIE": true,
    "CRYPTO ABE": true,
    "CRYPTO DREW": true,
    CSLG: true,
    CYNDI: true,
    DAN: true,
    DANIELLE: true,
    DANNY: true,
    DARIO: true,
    "DARK KNIGHT": true,
    DARREN: true,
    DAVID: true,
    "DAVID WU": true,
    DAYLI: true,
    "DC LAWYER": true,
    DEAN: true,
    DEBBY: true,
    DENIS: true,
    DENON: true,
    "DENTIST DAVE": true,
    "DERBY DOC": true,
    DEREK: true,
    DEW: true,
    DGAF: true,
    "di JAY": false,
    DJ: true,
    "DJ MELO D": true,
    "DJ WASHBURN": true,
    DK: true,
    "D'MANN": true,
    DNKY: true,
    DOC: true,
    DON: true,
    DONGER: true,
    "DONKEY SLAYER": true,
    "DOUBLE A": true,
    "DOUBLE M": true,
    DOUG: true,
    "DOUG POLK": true,
    DP: true,
    DQ: true,
    "DR. AC": true,
    "DR. DAVID": true,
    "DR. ELI": true,
    DREW: true,
    "DR. H": true,
    "DR. HAROON": true,
    "DR. H o": false,
    DRISS: true,
    "DR. P": true,
    "DR. PATEL": true,
    "D SOPES": true,
    DUSTIN: true,
    DYLAN: true,
    e: false,
    "e ARMENIAN MIKE": false,
    EDDIE: true,
    "EDDIE T": true,
    EDONK: true,
    EEMAUN: true,
    EFAN: true,
    EIDER: true,
    ELDAR: true,
    ELI: true,
    ELKY: true,
    ELY: true,
    EMIL: true,
    ENCORE: true,
    ENRIQUE: true,
    ENRY: true,
    ERIC: true,
    ERICH: true,
    "ERIC PERSSON": true,
    "ERIC SHANE": true,
    ERIK: true,
    ERIKA: true,
    ERNIE: true,
    ESHAAN: true,
    ESPEN: true,
    ETHAN: true,
    EUGENE: true,
    FABIAN: true,
    FADI: true,
    FAIZAL: true,
    FANG: true,
    "FANTASY JOE": true,
    "FAST EDDIE": true,
    "FAT AL": true,
    "FAT DUCK": true,
    "FAT SWEATER": true,
    FELIPE: true,
    FELIX: true,
    "FELT WARRIOR": true,
    FERDINAND: true,
    "FILET-O-FISH": true,
    FIRAS: true,
    "FLOP - WIN WITH 6/9": false,
    "FLOP - WIN WITH G/S": false,
    FRANCISCO: true,
    "FRANCISCO C": true,
    "FRANCISCO e": false,
    "FRANCISCO o": false,
    "FRANCISCO THE PRO": true,
    FRANCO: true,
    "FRANK G": true,
    FRANKIE: true,
    FRANKIE2CUPS: true,
    "FRANKIE NEXT GEN": true,
    FRECKLES: true,
    FRED: true,
    FREDDY: true,
    FRIEDBERG: true,
    "FUNKY PUNTS": true,
    GAL: true,
    "GANGSTER FRANK": true,
    GARRETT: true,
    "GARRETT LEIGHT": true,
    GARY: true,
    GASTON: true,
    GATORWADE: true,
    GAZZY: true,
    "GAZZY B": true,
    GENE: true,
    GEORGE: true,
    GILBERT: true,
    "GING TAO": true,
    "GLOBAL DANNY": true,
    GOOB: true,
    "GOOF-BALL": true,
    GRADY: true,
    GRAIL: true,
    "GREEDY GRANT": true,
    GREG: true,
    "GREG GOES ALL IN": true,
    GROUND: true,
    GT: true,
    "GUMMY BEAR": true,
    GUSTAVO: true,
    GUY: true,
    "GUY TOM": true,
    GYPSY: true,
    HADY: true,
    HAN: true,
    HANDZ: true,
    HANK: true,
    HANKS: true,
    HANSON: true,
    HARALABOS: true,
    HAROON: true,
    HARRY: true,
    HARSHEEL: true,
    HAYLEY: true,
    "HE HITS IT": true,
    HELLMUTH: true,
    HENRY: true,
    HH: true,
    HILARY: true,
    HILLARY: true,
    HISH: true,
    "HIVER - WIN J HIGH (on LESS)": false,
    HOLIDAY: true,
    HOLO: true,
    HOODIE: true,
    "HOODIE ALLEN": true,
    HOWARD: true,
    HRACH: true,
    "HUGE TIME": true,
    HUSKY: true,
    HUSS: true,
    HUSTLER: true,
    "HUSTLER BRIAN": true,
    I: false,
    IAN: true,
    "i JACK": false,
    "I MARS": true,
    "IRON BYTE": true,
    "ISRAELI RON": true,
    "I TAL": true,
    IVAN: true,
    "I WILL": true,
    JACK: true,
    "JACK NEXT GEN": true,
    JACKY: true,
    JAE: true,
    JAESH: true,
    JAHAAN: true,
    JAMI: true,
    JAMIE: true,
    JANE: true,
    JARIUS: true,
    JARRETT: true,
    JASON: true,
    JASPER: true,
    JAY: true,
    JBOOGS: true,
    "JBOOGS C": true,
    JC: true,
    JEFF: true,
    JEFFREY: true,
    JENX: true,
    JEREMY: true,
    JERRY: true,
    JESSE: true,
    JESSICA: true,
    JETMAN: true,
    JIANG: true,
    JIBRAEL: true,
    JIMMY: true,
    "JIMMY V": true,
    JJ: true,
    JL: true,
    JOE: true,
    "JOE COOL": true,
    JOEL: true,
    JOHN: true,
    "JOHN JOHN": true,
    "JOHNNIE VIBES": true,
    JOHNNY: true,
    "JOHNNY DOES IT": true,
    JON: true,
    JONAS: true,
    JONATHAN: true,
    JORDAN: true,
    JOSH: true,
    "J.R.": true,
    "    JRB": true,
    JT: true,
    JU: true,
    JULIA: true,
    JULIAN: true,
    JULIE: true,
    JULIO: true,
    JUN: true,
    JUNGLEMAN: true,
    JUNLIN: true,
    JUSTIN: true,
    JY: true,
    JZ: true,
    KANE: true,
    "KAPTAIN FISH": true,
    KAREN: true,
    KARIM: true,
    KAUFMAN: true,
    KEATING: true,
    KEIR: true,
    KEN: true,
    KENJI: true,
    KENNEDY: true,
    KENNY: true,
    KENT: true,
    "KEVIN LAX": true,
    "KEY FOB KING": true,
    KGB: true,
    KIAN: true,
    KIERO: true,
    KIM: true,
    KIRAN: true,
    "KIRAN C2B": true,
    KK: true,
    KLU: true,
    KOBI: true,
    "KOREAN DONKEY": true,
    KRISH: true,
    KUNGJ: false,
    KYLIE: true,
    KYM: true,
    L: true,
    "LAKER STEVE": true,
    LANDEN: true,
    LAW: true,
    LAWRENCE: true,
    LAWRENIT: true,
    LEE: true,
    LEO: true,
    "LEX 0": true,
    "LEX 0 o": false,
    LG: true,
    LINGLIN: true,
    "LING LING": true,
    "LIQUID STEVE": true,
    LIRON: true,
    "LITTLE FISH": true,
    LIVE: false,
    "LOCO CHINO": true,
    LOVEMAN: true,
    "LSG HANK": true,
    LUCAS: true,
    "LUCKBOX TONY": true,
    LUCKY: true,
    "LUDA CHRIS": true,
    "LUDA CHRIS e": false,
    "LUDA CHRIS o": false,
    LUDO: true,
    LUDWIG: true,
    LUIZ: true,
    LULU: true,
    LV: true,
    LYNNE: true,
    MAC: true,
    "MACAU BEN": true,
    MAGNUS: true,
    MARC: true,
    "MARC GOONE": true,
    MARG: true,
    MARGAUX: true,
    MARIAN: true,
    MARIANO: true,
    "MARIANO e": false,
    "MARIANO O": true,
    MARINA: true,
    MARIO: true,
    MARIUS: true,
    MARK: true,
    MARKUS: true,
    MARLE: true,
    MAROUANE53: true,
    MARS: true,
    "MARS O": true,
    MARTIN: true,
    MASATO: true,
    MATHEW: true,
    MATT: true,
    MATUSOW: true,
    MAX: true,
    "MAX VALUE MIKE": true,
    MAYHEM: true,
    "MEAN JEAN": true,
    MERGI: true,
    "MIA MEATBALL": true,
    MICAH: true,
    MICHAEL: true,
    "MICHAEL GUY": true,
    "MICHAEL L": true,
    MIGUEL: true,
    MIKE: true,
    "MIKE A": true,
    "MIKE BOOGIE": true,
    "MIKE e": false,
    "MIKE NIA": true,
    "MIKE X": true,
    "MIKEY ESQ.": true,
    "    MIKITA": true,
    MIKKI: true,
    MILES: true,
    MISHA: true,
    MJ: true,
    MO: true,
    MONEYMAKER: true,
    MORPHIS: true,
    MORRIS: true,
    "MR BEAST": true,
    "MR. DR. BATMAN": true,
    "MR. J": true,
    "MR. UNLUCKY": true,
    MUSILEK: true,
    NALDO: true,
    NATE: true,
    "NATE HILL": true,
    NEAL: true,
    NEMO: true,
    NEVE: true,
    NICK: true,
    "NICK A": true,
    "NICK AUSTIN": true,
    "NICK B": true,
    "NICK DALLA": true,
    "NICK L": true,
    "NICK LUCAS": true,
    "NICK NITUCCI": true,
    "NICK V": true,
    "NICK VERTUCCI": true,
    NIK: true,
    "NIK A": true,
    "NIK AIRBALL": true,
    "NIKKI LIMO": true,
    NIKOS: true,
    NINJA: true,
    NITUCCI: true,
    NIU: true,
    "NIU B": true,
    NJ: true,
    "NJ STELLA": true,
    "NON PROFIT PAUL": true,
    o: false,
    "OG MIKE": true,
    "OJ MELO D": true,
    OMAR: true,
    OMB: true,
    "ONE HEART": true,
    "ON TILT": true,
    "ORIENT EXPRESS": true,
    "ORIGINAL ELI": true,
    OSCAR: true,
    OZZY: true,
    PABLO: true,
    "PALMDALE MIKE": true,
    PANDA: true,
    PARKER: true,
    PATRICK: true,
    "PATRICK O": true,
    PATRIK: true,
    PAUL: true,
    "PAUL AHI": true,
    "PAUL C": true,
    "PAUL MALIBU": true,
    PAV: true,
    "PAWN SHOP CHRIS": true,
    PEDDY: true,
    PEDRO: true,
    "PENNZOIL DON": true,
    PEPE: true,
    PETE: true,
    PETER: true,
    "PETER THE REC": true,
    PHIL: true,
    "PHIL IVEY": true,
    PHORA: true,
    PIERSON: true,
    PINK: true,
    PIPI: true,
    PIZZA: true,
    "POCKET YAKIS": true,
    "POKER BUNNY": true,
    "POKER LLAMA": true,
    "POKER N CHILL": true,
    "POKER TRAVELER": true,
    POUDADDY: true,
    POUYA: true,
    "PRE-FLOP RAISE": false,
    "PRETTY BOY P": true,
    "PRINCE CHARLES": true,
    "PRINCESS LOVE": true,
    PROFESSOR: true,
    R88STER: true,
    RACHEL: true,
    "RAD ADI": true,
    "RAD CHANCE": true,
    "RAD ELI": true,
    RAHUL: true,
    "RAINBOW KITTY": true,
    RAMPAGE: true,
    RANDALL: true,
    RANDY: true,
    RAVER: true,
    "RAVER POKER": true,
    RAVIVO: true,
    RAY: true,
    "RAY D": true,
    "RAY J": true,
    RAYMOND: true,
    RB: true,
    RC: true,
    RECYCLER: true,
    RENE: true,
    REZA: true,
    "REZA #2": true,
    RICH: true,
    RICHARD: true,
    RICK: true,
    RICKY: true,
    RINA: true,
    RIP: true,
    "RIVER - WIN J HIGH (ON LESSI": false,
    "RIVER - WIN J HIGH (OR LESS)": false,
    RJ: true,
    ROB: true,
    ROBBI: true,
    ROCC: true,
    ROCKY: true,
    RONNIE: true,
    ROSCOE: true,
    "ROSEY NEXT GEN": true,
    RUBIEZ: true,
    RUFIO: true,
    RUSS: true,
    RYAN: true,
    "RYAN GARCIA": true,
    RYUSUKE: true,
    S: true,
    SAFIA: true,
    SALIM: true,
    SAM: true,
    SAMMY: true,
    "SAMMY MAC": true,
    "SAMMY THE BULL": true,
    SANDOR: true,
    SANDRO: true,
    "SAN MAN": true,
    SANTA: true,
    "SANTA O": true,
    SANTHOSH: true,
    SARA: true,
    SASABABI: true,
    SASHIMI: true,
    SAVA: true,
    SAYA: true,
    "SCARY TERI": true,
    SETH: true,
    SETHY: true,
    "SEXY CHRIS": true,
    SHANE: true,
    SHAUN: true,
    SHAWN: true,
    SHAY: true,
    SHELLI: true,
    SHINGO: true,
    "SHIP IT N SIP IT": true,
    SHOOTER: true,
    SHRIMP: true,
    SHY: true,
    SIA: true,
    SIAQIUUUU: true,
    "SIA THE BOT": true,
    SIMON: true,
    SINAN: true,
    "SIR TAO": true,
    SKILLSROCKS: true,
    SKYE: true,
    SLEEPY: true,
    "SLICK RIC": true,
    SLIME: true,
    "SLOW POKER": true,
    "S MARS": true,
    SNEAK: true,
    SOBY: true,
    "SOFAST ANTONIO": true,
    SOFIA: true,
    "SOFLO ANTONIO": true,
    SONNY: true,
    SOUZIROU: true,
    SPANIARD: true,
    SPARKS: true,
    SPARTAK: true,
    SRIV: true,
    STAAKKS: true,
    STAN: true,
    STANLEY: true,
    "STANLEY CHOI": true,
    "STANLEY TANG": true,
    STEDDIE: true,
    STEVE: true,
    STEVEN: true,
    STINER: true,
    STRAT: true,
    STUART: true,
    "SUITED SUPERMAN": true,
    SUN: true,
    SUNG: true,
    SUNNY: true,
    SUNSET: true,
    "SUPREME LA": true,
    SURF: true,
    "SWING KING": true,
    SYKO: true,
    T1000: true,
    TAFO: true,
    TAHA: true,
    TAL: true,
    TAN: true,
    TANA: true,
    TANG: true,
    TAO: true,
    TED: true,
    TERI: true,
    "TERI 2TIMES": true,
    "TERIYAKI MADNESS": true,
    "TERRY T": true,
    TEXAS: true,
    "TEXAS MIKE": true,
    THAENG: true,
    "THE ACCOUNTANT": true,
    "THE ASHMAN": true,
    "THE CHAIRMAN": true,
    "THE KING": true,
    "THE LIBRARIAN": true,
    "THE LION": true,
    "THE MOUTH": true,
    "THE RECYCLER": true,
    "THE TOURIST": true,
    TIGER: true,
    "TIGER KING": true,
    TIM: true,
    TITO: true,
    TJ: true,
    "TNA KIRSH": true,
    TODD: true,
    TOM: true,
    "TOM DWAN": true,
    TOMMY: true,
    "TOM T": true,
    TONY: true,
    "TONY G": true,
    "TONY TAG": true,
    "TOP G": true,
    TORRES: true,
    TREVOR: true,
    "TREY ATX": true,
    "TRICK TIME": true,
    "TSM REGINALD": true,
    TUCHMAN: true,
    TUCK: true,
    TURBO: true,
    "TURN - WIN WITH 2/7": false,
    TYLER: true,
    "TYLER A": true,
    "TYLER D": true,
    TYRONE: true,
    "U CALL U BIG": true,
    ULTURES: true,
    URI: true,
    V: true,
    VAHE: true,
    VARUN: true,
    "VC SAM": true,
    VDONK: true,
    "VEGAS VINH": true,
    VEINS: true,
    VELTRI: true,
    VERONICA: true,
    "VERSACE MARC": true,
    VIC: true,
    VICTOR: true,
    VIFFER: true,
    VINCE: true,
    VINCENT: true,
    VINH: true,
    VIXEN: true,
    VPIP: false,
    w: false,
    WADE: true,
    WASABI: true,
    WEI: true,
    WESLEY: true,
    WHOISWHO: true,
    WILL: true,
    WILLIAM: true,
    "WIN 4 HANDS IN A HOW": false,
    "WIN A HAME WITH G/S": false,
    "WIN A HAND WITH 6/9": false,
    "WIN A HAND WITH 712": false,
    "WIN A RAND WITH 6/9": false,
    "WIN # HAND WITH 7/2": false,
    "WINO POKER": true,
    WOB: true,
    WOLFGANG: true,
    "WOLFGANG POKER": true,
    WOODY: true,
    "WORLD WIDE WOB": true,
    "WPI Global": false,
    "WPT Global": false,
    XQC: true,
    XUAN: true,
    YANG: true,
    YANNI: true,
    YARA: true,
    YC: true,
    YDD: true,
    YEN: true,
    YENNIFER: true,
    YG: true,
    YK: true,
    YODA: true,
    "YOH VIRAL": true,
    "YOUNG MAN": true,
    "ZACH F": true,
    ZACK: true,
    "ZAK L": true,
    ZEO: true,
    ZHAO: true,
};
