export const allDataForShowFixture = [
    {
        date: "2023/06/15",
        entity_type: "player_appearance",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "appearance#player#alex#",
        pk: "player#alex",
        player: "alex",
        player_name: "ALEX",
        show: "dVs7ORBHsF0",
        show_name: "Sashimi, Kiran C2B, Israeli Ron & Mike X Play $10/20/40 - Commentary by Christian Soto",
        sk: "appearance#slug#dVs7ORBHsF0#",
    },
    {
        date: "2023/06/15",
        entity_type: "player_appearance",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "appearance#player#c2b#",
        pk: "player#c2b",
        player: "c2b",
        player_name: "C2B",
        show: "dVs7ORBHsF0",
        show_name: "Sashimi, Kiran C2B, Israeli Ron & Mike X Play $10/20/40 - Commentary by Christian Soto",
        sk: "appearance#slug#dVs7ORBHsF0#",
    },
    {
        date: "2023/06/15",
        entity_type: "player_appearance",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "appearance#player#faizal#",
        pk: "player#faizal",
        player: "faizal",
        player_name: "FAIZAL",
        show: "dVs7ORBHsF0",
        show_name: "Sashimi, Kiran C2B, Israeli Ron & Mike X Play $10/20/40 - Commentary by Christian Soto",
        sk: "appearance#slug#dVs7ORBHsF0#",
    },
    {
        date: "2023/06/15",
        entity_type: "player_appearance",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "appearance#player#israeliron#",
        pk: "player#israeliron",
        player: "israeliron",
        player_name: "ISRAELI RON",
        show: "dVs7ORBHsF0",
        show_name: "Sashimi, Kiran C2B, Israeli Ron & Mike X Play $10/20/40 - Commentary by Christian Soto",
        sk: "appearance#slug#dVs7ORBHsF0#",
    },
    {
        date: "2023/06/15",
        entity_type: "player_appearance",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "appearance#player#johnny#",
        pk: "player#johnny",
        player: "johnny",
        player_name: "JOHNNY",
        show: "dVs7ORBHsF0",
        show_name: "Sashimi, Kiran C2B, Israeli Ron & Mike X Play $10/20/40 - Commentary by Christian Soto",
        sk: "appearance#slug#dVs7ORBHsF0#",
    },
    {
        date: "2023/06/15",
        entity_type: "player_appearance",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "appearance#player#mikex#",
        pk: "player#mikex",
        player: "mikex",
        player_name: "MIKE X",
        show: "dVs7ORBHsF0",
        show_name: "Sashimi, Kiran C2B, Israeli Ron & Mike X Play $10/20/40 - Commentary by Christian Soto",
        sk: "appearance#slug#dVs7ORBHsF0#",
    },
    {
        date: "2023/06/15",
        entity_type: "player_appearance",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "appearance#player#nick#",
        pk: "player#nick",
        player: "nick",
        player_name: "NICK",
        show: "dVs7ORBHsF0",
        show_name: "Sashimi, Kiran C2B, Israeli Ron & Mike X Play $10/20/40 - Commentary by Christian Soto",
        sk: "appearance#slug#dVs7ORBHsF0#",
    },
    {
        date: "2023/06/15",
        entity_type: "player_appearance",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "appearance#player#sashimi#",
        pk: "player#sashimi",
        player: "sashimi",
        player_name: "SASHIMI",
        show: "dVs7ORBHsF0",
        show_name: "Sashimi, Kiran C2B, Israeli Ron & Mike X Play $10/20/40 - Commentary by Christian Soto",
        sk: "appearance#slug#dVs7ORBHsF0#",
    },
    {
        date: "2023/06/15",
        entity_type: "player_appearance",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "appearance#player#tal#",
        pk: "player#tal",
        player: "tal",
        player_name: "TAL",
        show: "dVs7ORBHsF0",
        show_name: "Sashimi, Kiran C2B, Israeli Ron & Mike X Play $10/20/40 - Commentary by Christian Soto",
        sk: "appearance#slug#dVs7ORBHsF0#",
    },
    {
        date: "2023/06/15",
        entity_type: "player_appearance",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "appearance#player#wei#",
        pk: "player#wei",
        player: "wei",
        player_name: "WEI",
        show: "dVs7ORBHsF0",
        show_name: "Sashimi, Kiran C2B, Israeli Ron & Mike X Play $10/20/40 - Commentary by Christian Soto",
        sk: "appearance#slug#dVs7ORBHsF0#",
    },
    {
        date: "2023/06/15",
        duration: 20165,
        entity_type: "show",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "show#",
        id: "dVs7ORBHsF0",
        operator: "hcl",
        pk: "operator#hcl",
        show_name: "Sashimi, Kiran C2B, Israeli Ron & Mike X Play $10/20/40 - Commentary by Christian Soto",
        sk: "show#date#2023/06/15#slug#dVs7ORBHsF0#",
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cc#player#alex#",
        gsi2pk: "stat_type#cc",
        gsi2sk: "stat#player#alex#slug#dVs7ORBHsF0#",
        pk: "player#alex",
        player: "alex",
        player_name: "ALEX",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cc#show#alex#",
        type: "cc",
        value: 37360,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cc#player#c2b#",
        gsi2pk: "stat_type#cc",
        gsi2sk: "stat#player#c2b#slug#dVs7ORBHsF0#",
        pk: "player#c2b",
        player: "c2b",
        player_name: "C2B",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cc#show#c2b#",
        type: "cc",
        value: 21390,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cc#player#faizal#",
        gsi2pk: "stat_type#cc",
        gsi2sk: "stat#player#faizal#slug#dVs7ORBHsF0#",
        pk: "player#faizal",
        player: "faizal",
        player_name: "FAIZAL",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cc#show#faizal#",
        type: "cc",
        value: 17120,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cc#player#johnny#",
        gsi2pk: "stat_type#cc",
        gsi2sk: "stat#player#johnny#slug#dVs7ORBHsF0#",
        pk: "player#johnny",
        player: "johnny",
        player_name: "JOHNNY",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cc#show#johnny#",
        type: "cc",
        value: 42480,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cc#player#mikex#",
        gsi2pk: "stat_type#cc",
        gsi2sk: "stat#player#mikex#slug#dVs7ORBHsF0#",
        pk: "player#mikex",
        player: "mikex",
        player_name: "MIKE X",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cc#show#mikex#",
        type: "cc",
        value: 17160,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cc#player#nick#",
        gsi2pk: "stat_type#cc",
        gsi2sk: "stat#player#nick#slug#dVs7ORBHsF0#",
        pk: "player#nick",
        player: "nick",
        player_name: "NICK",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cc#show#nick#",
        type: "cc",
        value: 24680,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cc#player#sashimi#",
        gsi2pk: "stat_type#cc",
        gsi2sk: "stat#player#sashimi#slug#dVs7ORBHsF0#",
        pk: "player#sashimi",
        player: "sashimi",
        player_name: "SASHIMI",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cc#show#sashimi#",
        type: "cc",
        value: 34840,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cc#player#tal#",
        gsi2pk: "stat_type#cc",
        gsi2sk: "stat#player#tal#slug#dVs7ORBHsF0#",
        pk: "player#tal",
        player: "tal",
        player_name: "TAL",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cc#show#tal#",
        type: "cc",
        value: 26410,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cc#player#wei#",
        gsi2pk: "stat_type#cc",
        gsi2sk: "stat#player#wei#slug#dVs7ORBHsF0#",
        pk: "player#wei",
        player: "wei",
        player_name: "WEI",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cc#show#wei#",
        type: "cc",
        value: 8070,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#alex#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#alex#slug#dVs7ORBHsF0#",
        pk: "player#alex",
        player: "alex",
        player_name: "ALEX",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#alex#",
        type: "cw",
        value: 27530,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#c2b#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#c2b#slug#dVs7ORBHsF0#",
        pk: "player#c2b",
        player: "c2b",
        player_name: "C2B",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#c2b#",
        type: "cw",
        value: 11760,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#faizal#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#faizal#slug#dVs7ORBHsF0#",
        pk: "player#faizal",
        player: "faizal",
        player_name: "FAIZAL",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#faizal#",
        type: "cw",
        value: -5180,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#johnny#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#johnny#slug#dVs7ORBHsF0#",
        pk: "player#johnny",
        player: "johnny",
        player_name: "JOHNNY",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#johnny#",
        type: "cw",
        value: 12480,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#mikex#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#mikex#slug#dVs7ORBHsF0#",
        pk: "player#mikex",
        player: "mikex",
        player_name: "MIKE X",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#mikex#",
        type: "cw",
        value: -21840,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#nick#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#nick#slug#dVs7ORBHsF0#",
        pk: "player#nick",
        player: "nick",
        player_name: "NICK",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#nick#",
        type: "cw",
        value: 5540,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#sashimi#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#sashimi#slug#dVs7ORBHsF0#",
        pk: "player#sashimi",
        player: "sashimi",
        player_name: "SASHIMI",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#sashimi#",
        type: "cw",
        value: 5840,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#tal#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#tal#slug#dVs7ORBHsF0#",
        pk: "player#tal",
        player: "tal",
        player_name: "TAL",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#tal#",
        type: "cw",
        value: -13560,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#wei#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#wei#slug#dVs7ORBHsF0#",
        pk: "player#wei",
        player: "wei",
        player_name: "WEI",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#wei#",
        type: "cw",
        value: 2290,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#pfr#player#alex#",
        gsi2pk: "stat_type#pfr",
        gsi2sk: "stat#player#alex#slug#dVs7ORBHsF0#",
        pk: "player#alex",
        player: "alex",
        player_name: "ALEX",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#pfr#show#alex#",
        type: "pfr",
        value: 12,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#pfr#player#c2b#",
        gsi2pk: "stat_type#pfr",
        gsi2sk: "stat#player#c2b#slug#dVs7ORBHsF0#",
        pk: "player#c2b",
        player: "c2b",
        player_name: "C2B",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#pfr#show#c2b#",
        type: "pfr",
        value: 21,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#pfr#player#faizal#",
        gsi2pk: "stat_type#pfr",
        gsi2sk: "stat#player#faizal#slug#dVs7ORBHsF0#",
        pk: "player#faizal",
        player: "faizal",
        player_name: "FAIZAL",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#pfr#show#faizal#",
        type: "pfr",
        value: 14,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#pfr#player#israeliron#",
        gsi2pk: "stat_type#pfr",
        gsi2sk: "stat#player#israeliron#slug#dVs7ORBHsF0#",
        pk: "player#israeliron",
        player: "israeliron",
        player_name: "ISRAELI RON",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#pfr#show#israeliron#",
        type: "pfr",
        value: 15,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#pfr#player#johnny#",
        gsi2pk: "stat_type#pfr",
        gsi2sk: "stat#player#johnny#slug#dVs7ORBHsF0#",
        pk: "player#johnny",
        player: "johnny",
        player_name: "JOHNNY",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#pfr#show#johnny#",
        type: "pfr",
        value: 12,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#pfr#player#mikex#",
        gsi2pk: "stat_type#pfr",
        gsi2sk: "stat#player#mikex#slug#dVs7ORBHsF0#",
        pk: "player#mikex",
        player: "mikex",
        player_name: "MIKE X",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#pfr#show#mikex#",
        type: "pfr",
        value: 25,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#pfr#player#nick#",
        gsi2pk: "stat_type#pfr",
        gsi2sk: "stat#player#nick#slug#dVs7ORBHsF0#",
        pk: "player#nick",
        player: "nick",
        player_name: "NICK",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#pfr#show#nick#",
        type: "pfr",
        value: 11,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#pfr#player#sashimi#",
        gsi2pk: "stat_type#pfr",
        gsi2sk: "stat#player#sashimi#slug#dVs7ORBHsF0#",
        pk: "player#sashimi",
        player: "sashimi",
        player_name: "SASHIMI",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#pfr#show#sashimi#",
        type: "pfr",
        value: 20,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#pfr#player#tal#",
        gsi2pk: "stat_type#pfr",
        gsi2sk: "stat#player#tal#slug#dVs7ORBHsF0#",
        pk: "player#tal",
        player: "tal",
        player_name: "TAL",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#pfr#show#tal#",
        type: "pfr",
        value: 21,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#pfr#player#wei#",
        gsi2pk: "stat_type#pfr",
        gsi2sk: "stat#player#wei#slug#dVs7ORBHsF0#",
        pk: "player#wei",
        player: "wei",
        player_name: "WEI",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#pfr#show#wei#",
        type: "pfr",
        value: 18,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#vpip#player#alex#",
        gsi2pk: "stat_type#vpip",
        gsi2sk: "stat#player#alex#slug#dVs7ORBHsF0#",
        pk: "player#alex",
        player: "alex",
        player_name: "ALEX",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#vpip#show#alex#",
        type: "vpip",
        value: 35,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#vpip#player#c2b#",
        gsi2pk: "stat_type#vpip",
        gsi2sk: "stat#player#c2b#slug#dVs7ORBHsF0#",
        pk: "player#c2b",
        player: "c2b",
        player_name: "C2B",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#vpip#show#c2b#",
        type: "vpip",
        value: 31,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#vpip#player#faizal#",
        gsi2pk: "stat_type#vpip",
        gsi2sk: "stat#player#faizal#slug#dVs7ORBHsF0#",
        pk: "player#faizal",
        player: "faizal",
        player_name: "FAIZAL",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#vpip#show#faizal#",
        type: "vpip",
        value: 59,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#vpip#player#israeliron#",
        gsi2pk: "stat_type#vpip",
        gsi2sk: "stat#player#israeliron#slug#dVs7ORBHsF0#",
        pk: "player#israeliron",
        player: "israeliron",
        player_name: "ISRAELI RON",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#vpip#show#israeliron#",
        type: "vpip",
        value: 45,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#vpip#player#johnny#",
        gsi2pk: "stat_type#vpip",
        gsi2sk: "stat#player#johnny#slug#dVs7ORBHsF0#",
        pk: "player#johnny",
        player: "johnny",
        player_name: "JOHNNY",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#vpip#show#johnny#",
        type: "vpip",
        value: 43,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#vpip#player#mikex#",
        gsi2pk: "stat_type#vpip",
        gsi2sk: "stat#player#mikex#slug#dVs7ORBHsF0#",
        pk: "player#mikex",
        player: "mikex",
        player_name: "MIKE X",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#vpip#show#mikex#",
        type: "vpip",
        value: 44,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#vpip#player#nick#",
        gsi2pk: "stat_type#vpip",
        gsi2sk: "stat#player#nick#slug#dVs7ORBHsF0#",
        pk: "player#nick",
        player: "nick",
        player_name: "NICK",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#vpip#show#nick#",
        type: "vpip",
        value: 23,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#vpip#player#sashimi#",
        gsi2pk: "stat_type#vpip",
        gsi2sk: "stat#player#sashimi#slug#dVs7ORBHsF0#",
        pk: "player#sashimi",
        player: "sashimi",
        player_name: "SASHIMI",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#vpip#show#sashimi#",
        type: "vpip",
        value: 36,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#vpip#player#tal#",
        gsi2pk: "stat_type#vpip",
        gsi2sk: "stat#player#tal#slug#dVs7ORBHsF0#",
        pk: "player#tal",
        player: "tal",
        player_name: "TAL",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#vpip#show#tal#",
        type: "vpip",
        value: 35,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#vpip#player#wei#",
        gsi2pk: "stat_type#vpip",
        gsi2sk: "stat#player#wei#slug#dVs7ORBHsF0#",
        pk: "player#wei",
        player: "wei",
        player_name: "WEI",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#vpip#show#wei#",
        type: "vpip",
        value: 27,
    },
];
