export const allStatsOfTypeFixture = [
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#alex#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#alex#slug#dVs7ORBHsF0#",
        pk: "player#alex",
        player: "alex",
        player_name: "ALEX",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#alex#",
        type: "cw",
        value: 27530,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#c2b#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#c2b#slug#dVs7ORBHsF0#",
        pk: "player#c2b",
        player: "c2b",
        player_name: "C2B",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#c2b#",
        type: "cw",
        value: 11760,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#faizal#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#faizal#slug#dVs7ORBHsF0#",
        pk: "player#faizal",
        player: "faizal",
        player_name: "FAIZAL",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#faizal#",
        type: "cw",
        value: -5180,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#johnny#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#johnny#slug#dVs7ORBHsF0#",
        pk: "player#johnny",
        player: "johnny",
        player_name: "JOHNNY",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#johnny#",
        type: "cw",
        value: 12480,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#mikex#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#mikex#slug#dVs7ORBHsF0#",
        pk: "player#mikex",
        player: "mikex",
        player_name: "MIKE X",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#mikex#",
        type: "cw",
        value: -21840,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#nick#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#nick#slug#dVs7ORBHsF0#",
        pk: "player#nick",
        player: "nick",
        player_name: "NICK",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#nick#",
        type: "cw",
        value: 5540,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#sashimi#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#sashimi#slug#dVs7ORBHsF0#",
        pk: "player#sashimi",
        player: "sashimi",
        player_name: "SASHIMI",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#sashimi#",
        type: "cw",
        value: 5840,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#tal#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#tal#slug#dVs7ORBHsF0#",
        pk: "player#tal",
        player: "tal",
        player_name: "TAL",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#tal#",
        type: "cw",
        value: -13560,
    },
    {
        entity_type: "player_stat",
        gsi1pk: "slug#dVs7ORBHsF0",
        gsi1sk: "stat#stat_type#cw#player#wei#",
        gsi2pk: "stat_type#cw",
        gsi2sk: "stat#player#wei#slug#dVs7ORBHsF0#",
        pk: "player#wei",
        player: "wei",
        player_name: "WEI",
        show: "dVs7ORBHsF0",
        sk: "stat#stat_type#cw#show#wei#",
        type: "cw",
        value: 2290,
    },
];
